name: "Build"

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Customise: Cron interval: 4 hourly
    - cron: "0 3,7,11,15,19,23 * * *"
  workflow_dispatch:
    inputs:
      regenerate:
        description: Enter csv of recipe slugs to specifically regenerate
        required: false
        type: string
      skip:
        description: Enter csv of recipe slugs to specifically skip
        required: false
        type: string
      verbose:
        description: Run recipe in verbose mode
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Customise: Total job run time limit
    timeout-minutes: 40
    steps:

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install -g sass terser html-minifier-terser

      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install python requirements
        run: pip install -r requirements.txt

      - name: Install calibre dependencies
        run: sudo apt-get update -y && sudo apt-get install --no-install-recommends -y libegl1 libopengl0

      - name: Install calibre
        run: |
          mkdir -p ~/calibre-bin
          wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin install_dir=~/calibre-bin isolated=y
          export PATH=$PATH:$HOME/calibre-bin/calibre
          calibre --version
          echo "$HOME/calibre-bin/calibre" >> $GITHUB_PATH

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: cache
          key: cache

      - name: Generate .mobi
        env:
          CALIBRE_CONFIG_DIRECTORY: ${{ github.workspace }}/calibre_config/
          regenerate: ${{ github.event.inputs.regenerate }}
          skip: ${{ github.event.inputs.skip }}
          verbose: ${{ github.event.inputs.verbose }}
        run: |
          export CI_PAGES_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io${GITHUB_REPOSITORY:${#GITHUB_REPOSITORY_OWNER}}/"
          sh _build.sh
          if [[ -f 'job_summary.md' ]]; then cat 'job_summary.md' >> $GITHUB_STEP_SUMMARY; fi
          echo -e "\n<"'!'"-- Commit ${GITHUB_SHA:0:7} -->" >> public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
